language: node_js
node_js:
  - 12
services:
  - postgresql
before_script:
  - psql -f db/install.sql -U postgres
  - PGPASSWORD=marcus psql -d application -f db/database.sql -U marcus
script:
  - npm test
